apiVersion: v1
kind: Secret

metadata:
  name: barberbooking-secret
  namespace: barber-booking

type: Opaque

stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "REPLACE_WITH_POSTGRES_PASSWORD"

  Jwt__SigningKey: "REPLACE_WITH_JWT_SIGNING_KEY"
  RefreshTokens__Pepper: "REPLACE_WITH_REFRESH_TOKEN_PEPPER"